# This is a basic workflow to help you get started with Actions

name: Blogit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: blogit-bot
        # You may pin to the exact commit or the version.
        # uses: renzholy/blogit@cf891af0fb29eebf5ad525f8552696385da9c895
        uses: renzholy/blogit@v0.0.18
        env:
          NEXT_PUBLIC_OWNER: kastnerorz
          NEXT_PUBLIC_REPO: kastnerorz.github.io
          NEXT_PUBLIC_BRANCH: master
          NEXT_PUBLIC_TITLE: Zed.log
          NEXT_PUBLIC_INDEX: /readme
          NEXT_PUBLIC_LINKS: Home,/readme;About,/about;GitHub,https://github.com/kastnerorz;Twitter,http://twitter.com/kastnerorz;Jike,https://web.okjike.com/u/5c8de6be-4e14-4bf5-b02a-7a97ae19c246
